# Change these first
owner: vanillahr # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Website
    url: https://www.vanillahr.com
  - name: Auth
    url: https://auth.vanillahr.com
  - name: API
    url: https://api.vanillahr.com/v1/auth
  - name: API
    url: https://api.vanillahr.com/v1/form

status-website:
  # cname: status.vanillahr.com
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/vanillahr/status/master/assets/vanillahr.svg
  #themeUrl: https://raw.githubusercontent.com/vanillahr/status/master/assets/purple.css
  #favicon: https://raw.githubusercontent.com/vanillahr/status/master/assets/vanillahr-icon.png
  name: Status Page
  introTitle: ""
  introMessage: ""
  navbar:

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

